services:
  - type: web
    name: pillarboxd-server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: "8000"
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: pillarboxd-client
          property: host
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PUB
        sync: false
      - key: SUPABASE_SECRET
        sync: false
      - key: TVDB_READ_TOKEN
        sync: false
      - key: TVDB_KEY
        sync: false

  - type: web
    name: pillarboxd-client
    runtime: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: .
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: pillarboxd-server
          property: host
